### ISSUE TITLE
IndexOutOfBoundsException from ChatActivity

### ISSUE THREAD

**Issue by imranMnts** [dimelo/Dimelo-Android#51] opened 2019-12-10 08:10 UTC
**Description**

I use Dimelo SDK in my project, it works properly except sometimes which causes crashes on some devices (often Samsung) with this error

`Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1cad317 position=23 id=-1, oldPos=22, pLpos:22 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{ab4b22 VFED.V... ......ID 0,0-1080,687 #7f0902c4 app:id/message_list}, adapter:com.dimelo.dimelosdk.main.DimeloChatAdapter@81f89b3, layout:android.support.v7.widget.LinearLayoutManager@4d45b70, context:com.dimelo.dimelosdk.main.ChatActivity@ea5398f
       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition + 5610(RecyclerView.java:5610)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline + 5792(RecyclerView.java:5792)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition + 5752(RecyclerView.java:5752)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition + 5748(RecyclerView.java:5748)`

I display dimelo into the activity provided by the SDK:

`Dimelo.getInstance().openChatActivity(context, intent)`

**Additional Information**

    SDK version: 1.7.2
    OS version: android 6 to 9

**Comment by waelba** [comment] 2019-12-10 10:52
Hi @imranMnts,
can you please test with the **latest sdk version (v1.8.0)** and tell me if the problem is still persist ?
Thanks,

**Comment by imranMnts** [comment] 2019-12-10 13:33
@wa-el I will try, thank you 🙂

**Comment by imranMnts** [comment] 2019-12-31 11:22
Hello @wa-el 
The issue still here with the latest SDK version v1.8.0

**Comment by jfgrim** [comment] 2020-11-17 10:35
Hi, I am getting the same with version 1.9.1 and 1.8.0. As soon as the activity and its fragment receives a new message from my customer service, there is a Crash:
  --------- beginning of crash
2020-11-17 10:46:28.682 6845-6845/fr.xxx.xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.xxx.xxx.xxx, PID: 6845
    java.lang.: Inconsistency detected. Invalid view holder adapter positionAgentMessageViewHolder{d6e315c position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{691432a VFED.V... ......ID 0,0-1080,1892 #7f0802c7 app:id/message_list}, adapter:com.dimelo.dimelosdk.main.DimeloChatAdapter@acc951b, layout:androidx.recyclerview.widget.LinearLayoutManager@c6be6b8, context:fr.XXXX.XXX.XXXChatActivity@d1ec17b
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4085)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
        at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:530)
        at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1099)
2020-11-17 10:46:28.682 6845-6845/fr.xxx.xxx.xxx E/AndroidRuntime:     at android.view.View.layout(View.java:23750)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3712)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3164)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by jfgrim** [comment] 2020-11-17 11:35
I found: when I receive a notification (with Firebase) I mistakenly created a second instance of Dimelo.

**Comment by waelba** [comment] 2020-12-02 12:46
Thanks @jfgrim! I'm closing this issue, feel free to create a new one if you have another question 🙂

**Closed as completed by waelba** 2020-12-02 12:46 UTC
